# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build development

on:
  push:
    branches:
    - development

defaults:
  run:
    shell: bash
    working-directory: angular

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        npm install
        npm run lint
        docker build .. -t wartemis/frontend:${{ github.sha }}
        docker run -dit -p 8080:80 wartemis/frontend
