# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build development

on:
  push:
    branches:
    - development

defaults:
  run:
    shell: bash
    working-directory: angular

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run lint
    # - run: npm run test # temporarily disabled untill tests are implemented
    - run: npm run e2e # temporarily disabled untill tests are implemented
    - run: npm run build
