name: build

on:
  push:
    branches:
    - master
    - development

defaults:
  run:
    shell: bash
    working-directory: angular

env:
  NODE_VERSION: 12.x

jobs:
  build:
    runs-on: self-hosted
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{env.NODE_VERSION}}

    - name: Install
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Compile
      run: npm run prod

    - name: Docker
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: wartemis/frontend
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
