name: build development

on:
  push:
    branches:
    - development

defaults:
  run:
    shell: bash
    working-directory: angular

env:
  NODE_VERSION: 12.x

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{env.NODE_VERSION}}
    - name: Retrieve cache
      uses: actions/cache@v1
      with:
        path: angular/node_modules
        key: node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Compile
      run: npm run build
    - name: Build
      run: docker build .. -t wartemis/frontend:development
    - name: Run
      run: docker run -dit -p 8080:80 wartemis/frontend:development
